### ISSUE TITLE
Upload via local-only mode not working

### ISSUE THREAD

**Issue by poguez** [newsdev/stevedore#24]
Running on Fedora 24 with:

```
openjdk version "1.8.0_102"
OpenJDK Runtime Environment (build 1.8.0_102-b14)
OpenJDK 64-Bit Server VM (build 25.102-b14, mixed mode)
```

I am trying tot run the jar and I get an error when I set up  the local-only mode.

```
0:0:0:0:0:0:0:1 -  [01/Sep/2016:13:48:08 +0900] "GET /upload/stream " 200 140 0.0040
Invalid: []
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:25: warning: already initialized constant PKCS1_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:25: warning: already initialized constant SSLV23_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:25: warning: already initialized constant NO_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:25: warning: already initialized constant PKCS1_OAEP_PADDING
2016-09-01 13:48:10 - LoadError - load error: jopenssl/load -- java.lang.SecurityException: class "org.bouncycastle.asn1.ASN1Primitive"'s signer information does not match signer information of other classes in the same package:
    org/jruby/RubyKernel.java:937:in `require'
    uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54:in `require'
    uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/openssl.rb:1:in `<top>'
    org/jruby/RubyKernel.java:937:in `require'
    uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54:in `require'
    uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/https.rb:1:in `<top>'
    org/jruby/RubyKernel.java:937:in `require'
    uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54:in `require'
    uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/https.rb:22:in `<top>'
    org/jruby/RubyKernel.java:937:in `require'
    uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54:in `require'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/stevedore-uploader-1.0.3-java/lib/stevedore-uploader.rb:1:in `block in (root)'
    org/jruby/RubyMethod.java:111:in `call'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/stevedore-uploader-1.0.3-java/lib/stevedore-uploader.rb:6:in `block in (root)'
    org/jruby/RubyProc.java:318:in `call'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block in route!'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block in route!'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
    org/jruby/RubyKernel.java:1096:in `catch'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
    org/jruby/RubyArray.java:1560:in `each'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
    org/jruby/RubyKernel.java:1096:in `catch'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
    org/jruby/RubyKernel.java:1096:in `catch'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:212:in `call'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
    org/jruby/RubyArray.java:1560:in `each'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/rack-1.6.4/lib/rack/static.rb:124:in `call'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/rack-1.6.4/lib/rack/static.rb:124:in `call'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/rack-1.6.4/lib/rack/static.rb:124:in `call'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/rack-1.6.4/lib/rack/static.rb:124:in `call'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
    org/jruby/RubyArray.java:1560:in `each'
    /tmp/jetty-0.0.0.0-8080-stevedore.jar-_-any-6626554525561569016.dir/webapp/WEB-INF/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
    uri:classloader:/rack/handler/servlet.rb:22:in `call'
0:0:0:0:0:0:0:1 -  [01/Sep/2016:13:48:10 +0900] "POST /upload/do " 500 30 0.0690



```

**Comment by jeremybmerrill** [comment]
Ah, yeah. I'm familiar with this bug, unfortunately. I'll try to rebuild a version that works soon.

**Comment by jeremybmerrill** [comment]
Do you have any versions of bouncycastle on your classpath or anything like that?

**Comment by jeremybmerrill** [comment]
Hi @poguez does this version work for you? https://www.dropbox.com/s/i1umfnbu9ke4ngi/stevedore.jar?dl=0

**Comment by poguez** [comment]
Let me try @jeremybmerrill :+1:

**Comment by poguez** [comment]
It is working!

Thank you.

**Comment by jeremybmerrill** [comment]
Glad to hear it!
